---
defaults:
  - best_month/tcmoran@_here_
  - _self_

train_transforms: 
  _target_: src.data.transforms.Compose
  transforms:
    - _target_: src.data.transforms.ClampAGBM
      vmin: 0.0
      vmax: 500.0

eval_transforms:
  _target_: src.data.transforms.Identity
