---
defaults:
  - /schema/dm: base
  - _self_
train_batch_size: 16
eval_batch_size: null
num_workers: 0
persist_workers: false
pin_memory: true
root: '/srv/galene0/shared/data/biomassters/'
tile_dir: null
group_by: CHIP
preprocess: true
n_pp_jobs: 4
split_seed: 47
val_prop: 0.2
test_prop: null
train_transforms: 
  _target_: src.data.transforms.Compose
  transforms:
    - _target_: src.data.transforms.Flatten
      start_dim: 0
      end_dim: 1
    - _target_: src.data.transforms.ClampAGBM
      vmin: 0.0
      vmax: 500.0
    - _target_: src.data.transforms.MinMaxNormalizeTarget
      orig_min: 0.0
      orig_max: 500.0
      new_min: 0.0
      new_max: 1.0

eval_transforms:
  _target_: src.data.transforms.Flatten
  start_dim: 0
  end_dim: 1
