---
defaults:
  - all_months/base@_here_
  - _self_

missing_value: INF
train_transforms: 
  _target_: src.data.transforms.Compose
  transforms:

    - _target_: src.data.transforms.NanToNum
      posinf:
        - 0.0000
        - 0.0000
        - 0.0000
        - 0.0000
        - 0.0000
        - 0.0000
        - 0.0000
        - 0.0000
        - 0.0000
        - 0.0000
        - 255.0000
        - -25.0000
        - -62.4062
        - -10000.0000
        - -10000.0000

    # - _target_: src.data.transforms.RandomResizedCrop
    #   p: 1.0
    #   size: ${tuple:256,256}
    #   scale: ${tuple:0.4,1.0}

    # - _target_: src.data.transforms.ApplyToS2
    #   transform:
    #     _target_: src.data.transforms.RandomErasing
    #     p: 0.1
    #     scale: ${tuple:0.02,0.33}
    #     ratio: ${tuple:0.3,3.3}
    #     same_on_batch: false
    #     channelwise: true

    - _target_: src.data.transforms.ZScoreNormalizeInput
      mean: 
      - 1630.7314
      - 1613.0652
      - 1602.6263

      - 1921.5253
      - 2485.7937
      - 2598.2380
      - 2746.1973
      - 2693.2007
      - 1029.7616
      - 699.9008
      - 21.4513
      - -11.4403
      - -18.0565
      - -1194.7567
      - -1200.6406
      std: 
      - 2.5042e+03
      - 2.3169e+03
      - 2.3942e+03

      - 2.3952e+03
      - 2.2154e+03
      - 2.1094e+03
      - 2.1993e+03
      - 2.0354e+03
      - 9.3802e+02
      - 7.6325e+02
      - 4.9878e+01
      - 3.1816e+00
      - 4.3850e+00
      - 3.2280e+03
      - 3.2258e+03

    # - _target_: src.data.transforms.RandomErasing
    #   p: 0.3
    #   scale: ${tuple:0.02,0.33}
    #   ratio: ${tuple:0.3,3.3}
    #   same_on_batch: false


    # - _target_: src.data.transforms.RandomGaussianBlur
    #   p: 0.2
    #   kernel_size: ${tuple:3,3}
    #   sigma: ${tuple:0.1,2.0}
    #   same_on_batch: false

    # - _target_: src.data.transforms.RandomGaussianNoise
    #   p: 0.2
    #   std: 0.1

    - _target_: src.data.transforms.RandomHorizontalFlip
      p: 0.5

    - _target_: src.data.transforms.RandomRotation
      p: 0.75

    - _target_: src.data.transforms.ZScoreNormalizeTarget
      mean: 63.3297
      std: 71.8312
    # - _target_: src.data.transforms.Log1pNormalizeTarget

eval_transforms:
  _target_: src.data.transforms.Compose
  transforms:
    - _target_: src.data.transforms.NanToNum
      posinf:
        - 0.0000
        - 0.0000
        - 0.0000
        - 0.0000
        - 0.0000
        - 0.0000
        - 0.0000
        - 0.0000
        - 0.0000
        - 0.0000
        - 255.00
        - -25.0000
        - -62.4062
        - -10000.0000
        - -10000.0000

    - _target_: src.data.transforms.ZScoreNormalizeInput
      mean: 
      - 1630.7314
      - 1613.0652
      - 1602.6263

      - 1921.5253
      - 2485.7937
      - 2598.2380
      - 2746.1973
      - 2693.2007
      - 1029.7616
      - 699.9008
      - 21.4513
      - -11.4403
      - -18.0565
      - -1194.7567
      - -1200.6406
      std: 
      - 2.5042e+03
      - 2.3169e+03
      - 2.3942e+03

      - 2.3952e+03
      - 2.2154e+03
      - 2.1094e+03
      - 2.1993e+03
      - 2.0354e+03
      - 9.3802e+02
      - 7.6325e+02
      - 4.9878e+01
      - 3.1816e+00
      - 4.3850e+00
      - 3.2280e+03
      - 3.2258e+03
