---
defaults:
  - all_months/base@_here_
  - _self_

missing_value: INF
train_transforms: 
  _target_: src.data.transforms.Compose
  transforms:
    - _target_: src.data.transforms.Sentinel1Scaler
    - _target_: src.data.transforms.Sentinel2Scaler
    - _target_: src.data.transforms.NanToNum
      nan: 0.0
      posinf: 0.0
      neginf: 0.0
    - _target_: src.data.transforms.ClampAGBM
      vmin: 0.0
      vmax: 500.0
    # - _target_: src.data.transforms.MinMaxNormalizeTarget
    #   orig_min: 0.0
    #   orig_max: 500.0
    #   new_min: 0.0
    #   new_max: 1.0

eval_transforms:
  _target_: src.data.transforms.Compose
  transforms:
    - _target_: src.data.transforms.Sentinel1Scaler
    - _target_: src.data.transforms.Sentinel2Scaler
    - _target_: src.data.transforms.NanToNum
      nan: 0.0
      posinf: 0.0
      neginf: 0.0
