---
defaults:
  - all_months/base@_here_
  - _self_

missing_value: INF
train_transforms: 
  _target_: src.data.transforms.Compose
  transforms:

    - _target_: src.data.transforms.Transpose
      dim0: 0
      dim1: 1
    - _target_: torchgeo.transforms.indices.AppendNDVI
      index_nir: 6
      index_red: 2
    - _target_: torchgeo.transforms.indices.AppendNormalizedDifferenceIndex
      index_a: 11
      index_b: 12
    - _target_: torchgeo.transforms.indices.AppendNDBI
      index_swir: 8 
      index_nir: 6
    - _target_: torchgeo.transforms.indices.AppendNDRE
      index_nir: 6 
      index_vre1: 3
    - _target_: torchgeo.transforms.indices.AppendNDSI
      index_green: 1
      index_swir: 8
    - _target_: torchgeo.transforms.indices.AppendNDWI
      index_green: 1
      index_nir: 6
    - _target_: torchgeo.transforms.indices.AppendSWI
      index_vre1: 3
      index_swir2: 8
    - _target_: src.data.transforms.AppendRatioAB
      index_a: 11
      index_b: 12
    - _target_: src.data.transforms.AppendRatioAB
      index_a: 13
      index_b: 14
    - _target_: src.data.transforms.Transpose
      dim0: 0
      dim1: 1

    - _target_: src.data.transforms.ZScoreNormalizeInput
      mean: 
      - 1630.7314
      - 1613.0652
      - 1602.6263
      - 1921.5253
      - 2485.7937
      - 2598.2380
      - 2746.1973
      - 2693.2007
      - 1029.7616
      - 699.9008
      - 21.4513
      - -11.4403
      - -18.0565
      - -1194.7567
      - -1200.6406
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      std: 
      - 2.5042e+03
      - 2.3169e+03
      - 2.3942e+03
      - 2.3952e+03
      - 2.2154e+03
      - 2.1094e+03
      - 2.1993e+03
      - 2.0354e+03
      - 9.3802e+02
      - 7.6325e+02
      - 4.9878e+01
      - 3.1816e+00
      - 4.3850e+00
      - 3.2280e+03
      - 3.2258e+03
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1

    - _target_: src.data.transforms.NanToNum
      nan: 0.0
      posinf: 0.0
      neginf: 0.0

    # - _target_: src.data.transforms.RandomResizedCrop
    #   p: 1.0
    #   size: ${tuple:256,256}
    #   scale: ${tuple:0.4,1.0}

    - _target_: src.data.transforms.RandomGaussianBlur
      p: 0.2
      kernel_size: ${tuple:3,3}
      sigma: ${tuple:0.1,2.0}

    # - _target_: src.data.transforms.RandomErasing
    #   p: 0.1
    #   scale: ${tuple:0.02,0.33}
    #   ratio: ${tuple:0.3,3.3}

    - _target_: src.data.transforms.RandomHorizontalFlip
      p: 0.5

    - _target_: src.data.transforms.RandomRotation
      p: 0.75

    - _target_: src.data.transforms.ZScoreNormalizeTarget
      mean: 63.3297
      std: 71.8312

eval_transforms:
  _target_: src.data.transforms.Compose
  transforms:
    - _target_: src.data.transforms.Transpose
      dim0: 0
      dim1: 1
    - _target_: torchgeo.transforms.indices.AppendNDVI
      index_nir: 6
      index_red: 2
    - _target_: torchgeo.transforms.indices.AppendNormalizedDifferenceIndex
      index_a: 11
      index_b: 12
    - _target_: torchgeo.transforms.indices.AppendNDBI
      index_swir: 8 
      index_nir: 6
    - _target_: torchgeo.transforms.indices.AppendNDRE
      index_nir: 6 
      index_vre1: 3
    - _target_: torchgeo.transforms.indices.AppendNDSI
      index_green: 1
      index_swir: 8
    - _target_: torchgeo.transforms.indices.AppendNDWI
      index_green: 1
      index_nir: 6
    - _target_: torchgeo.transforms.indices.AppendSWI
      index_vre1: 3
      index_swir2: 8
    - _target_: src.data.transforms.AppendRatioAB
      index_a: 11
      index_b: 12
    - _target_: src.data.transforms.AppendRatioAB
      index_a: 13
      index_b: 14
    - _target_: src.data.transforms.Transpose
      dim0: 0
      dim1: 1

    - _target_: src.data.transforms.ZScoreNormalizeInput
      mean: 
      - 1630.7314
      - 1613.0652
      - 1602.6263
      - 1921.5253
      - 2485.7937
      - 2598.2380
      - 2746.1973
      - 2693.2007
      - 1029.7616
      - 699.9008
      - 21.4513
      - -11.4403
      - -18.0565
      - -1194.7567
      - -1200.6406
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      std: 
      - 2.5042e+03
      - 2.3169e+03
      - 2.3942e+03
      - 2.3952e+03
      - 2.2154e+03
      - 2.1094e+03
      - 2.1993e+03
      - 2.0354e+03
      - 9.3802e+02
      - 7.6325e+02
      - 4.9878e+01
      - 3.1816e+00
      - 4.3850e+00
      - 3.2280e+03
      - 3.2258e+03
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1

    - _target_: src.data.transforms.NanToNum
      nan: 0.0
      posinf: 0.0
      neginf: 0.0
